#!/bin/sh -e
NAME=aesdsocket
DAEMON=aesdsocket
DAEMON_ARGS="-d"
STOP_SIGNAL=SIGTERM
common_opts="--quiet"

do_start(){
    start-stop-daemon -S -n $DAEMON $DAEMON_ARGS
    ;;
}

do_stop(){
    opt=${@:-}
    start-stop-daemon -K -n --signal $STOP_SIGNAL
    ;;
}

do_status(){
    start-stop-daemon --status $common_opts && exit_status=$? || exit_status=$?
    echo asdf $exit_status
    case "$exit_status" in
        0)
            echo "Program '$NAME' is running."
            ;;
        1)
            echo "Program '$NAME' is not running and the pid file exists."
            ;;
        3)
            echo "Program '$NAME' is not running."
            ;;
        4)
            echo "Unable to determine program '$NAME' status."
            ;;
    esac
}

case "$1" in
  status)
        do_status
        ;;
  start)
        echo -n "Starting daemon: "$NAME
        do_start
        echo "."
        ;;
  stop)
        echo -n "Stopping daemon: "$NAME
        do_stop
        echo "."
        ;;
  restart)
        echo -n "Restarting daemon: "$NAME
        do_stop --retry 30
        do_start
        echo "."
        ;;
  *)
        echo "Usage: "$1" {status|start|stop|restart}"
        exit 1
esac

